# Short-Cut Version: 45 Scenes

user = "James"
dialoguesCut = [
    # Prelude + Part.1 -> Begins
    {
        "scnImg": "dreamCrowd1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator - Beginning", 
        "body": f'''The Story Begins as {user} stands before a room filled with colleagues, employees, and the highly esteemed Chief Guest. ''', 
        "emotional": False, 
        "Next": 1, 
    }, 
    {
        "scnImg": "dreamCrowd3.jpg", 
        "chrImg": "dreamPWangdu.png", 
        "name": f"The Chief Guest", 
        "body": f'''(With Admiration) {user}, your vision is inspiring, and your leadership is commendable. We have a bright future ahead of us. ''', 
        "emotional": False, 
        "Next": 2, 
    }, 
    {
        "scnImg": "dreamCrowd3.jpg", 
        "chrImg": "dreamPWangdu.png", 
        "name": f"The Chief Guest", 
        "body": f'''(Announcing) So, Ladies and gentlemen, I am proud to endorse {user} as your CEO for our upcoming collabs.''', 
        "emotional": False, 
        "Next": 3, 
    }, 
    {
        "scnImg": "dreamCrowd2.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''The room erupts in applause. {user} is on the verge of a life-changing moment. ''', 
        "emotional": False, 
        "Next": 4, 
    }, 
    {
        "scnImg": "dreamCrowd2.jpg", 
        "chrImg": "verma.png", 
        "name": f"{user} (You) - Whispering", 
        "body": f'''Oh... Finally, it is going about to happen. For Real!''', 
        "emotional": True, 
        "Points": {"Anger": -30, "Fear": -10, "Happy": 50, "Disgust": -30, "Surprise": 10, "Neutral": 10, "Sad": 10}, 
        "Anger": '(Aggressive) Finish it quickly you slowpokes!', 
        "Fear": '(Fearful) I don\'t know what challenge awaits me next.', 
        "Happy": '(Joyous) I can see my dream coming true.', 
        "Disgust": '(Feeling Unwell) I don\'t know why but this sucks!', 
        "Surprise": 'OMG! I didn\'t expect this to happen this smoothly.', 
        "Neutral": 'Whatever, this is nothing, many more to come.', 
        "Sad": '(Emotional) This is the best day of My Life.', 
        "End": 'Let\'s proceed now.', 
        "Next": 5, 
    }, 
    {
        "scnImg": "dreamCrowd1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''As the Chief Guest resumed to speak . . . ''', 
        "emotional": False, 
        "Next": 6, 
    },  
    # Prelude -> Ends   
    {
        "scnImg": "drmBreak.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''A cacophony of vehicle horns outside {user}'s window shattered the lovely dream. ''', 
        "emotional": False, 
        "Next": 7, 
    }, 
    {
        "scnImg": "bedrm1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''Startled, he was disoriented and momentarily unsure if the success in his dream was real or a mere figment of his imagination.''', 
        "emotional": False, 
        "Next": 8, 
    }, 
    {
        "scnImg": "bedrm2.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''With the scent of fresh coffee, {user} stood up, and saw his wife, Monika. She smiled warmly at him.''', 
        "emotional": False, 
        "Next": 9, 
    }, 
    {
        "scnImg": "house1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''{user} nods. He knew it was time to get ready. As the morning wore on, {user} dressed meticulously in his finest suit and tie.''', 
        "emotional": False, 
        "Next": 10, 
    }, 
    {
        "scnImg": "house2.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''{user} is leaving for the venue. Monika stands in front of the door to say Goodbye.''', 
        "emotional": False, 
        "Next": 11, 
    }, 
    {
        "scnImg": "house2.jpg", 
        "chrImg": "monika2.png", 
        "name": f"Monika (Your Wife)", 
        "body": f'''Are you ready for your summit today? Make sure you amaze them OK. All the Best!!!''', 
        "emotional": False, 
        "Next": 12, 
    }, 
    {
        "scnImg": "house2.jpg", 
        "chrImg": "verma.png", 
        "name": f"{user} (You)", 
        "body": f'''(Slightly Tensed as Time Progresses)''', 
        "emotional": True, 
        "Points": {"Anger": -100, "Fear": -25, "Happy": 100, "Disgust": -30, "Surprise": -25, "Neutral": 50, "Sad": -50}, 
        "Anger": 'GEEZ, don\'t startle me like that, I am already under a lot of pressure here. Why do you have to always be so annoying.', 
        "Fear": '(Panicking) I don\'t know about that, I am feeling very nervous.', 
        "Happy": '(Smiling) Thanks Monika, Just wait and watch while I blow their socks off.', 
        "Disgust": '(Seeming Unwell) I don\'t know about that, I am feeling very nervous.', 
        "Surprise": '(Panicking) GEEZ, don\'t startle me like that, I am already under a lot of pressure here.', 
        "Neutral": '(Calmly) Thanks Monika, Just wait and watch while I blow their socks off.', 
        "Sad": 'I don\'t know about that, I am feeling very nervous.', 
        "End": 'Okay then, Goodbye Monika. I have to reach there ASAP.', 
        "Next": 13, 
    }, 
    {
        "scnImg": "rdBgn1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''{user} gets in his car, and sets out for X's Summit Center which is located in the heart of the iconic Mumbai City.''', 
        "emotional": False, 
        "Next": 14, 
    }, 
    {
        "scnImg": "trafic1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''But soon he encounters a sea of vehicles, stretched as far as the eye could see, locked in a seemingly endless traffic jam.''', 
        "emotional": False, 
        "Next": 15, 
    }, 
    {
        "scnImg": "rdBlk1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''{user} knew a cut that leads to the venue. But his path was blocked by a black BMW. He tries to talk to the driver.''', 
        "emotional": False, 
        "Next": 16, 
    }, 
    {
        "scnImg": "rdBlk2.jpg", 
        "chrImg": "verma.png", 
        "name": f"{user} (You)", 
        "body": f'''(With a Sense of Urgency) Excuse me, could you please move out of the way? I really need to take a shortcut.''', 
        "emotional": False, 
        "Next": 17, 
    }, 
    {
        "scnImg": "rdBlk3.jpg", 
        "chrImg": "nina.png", 
        "name": f"The Stranger", 
        "body": f'''(Sympathetic) I totally get it. I'm running late too.''', 
        "emotional": False, 
        "Next": 18, 
    }, 
    {
        "scnImg": "rdBlk3.jpg", 
        "chrImg": "nina.png", 
        "name": f"The Stranger", 
        "body": f'''But it's a tight squeeze, and I don't want to damage my car. Can you please wait until I get enough space to move out of your way?''', 
        "emotional": False, 
        "Next": 19, 
    }, 
    {
        "scnImg": "rdBlk2.jpg", 
        "chrImg": "verma.png", 
        "name": f"{user} (You)", 
        "body": f'''(Muttering) I can\'t waste my time waiting here though . . .''', 
        "emotional": True, 
        "Points": {"Anger": -100, "Fear": -25, "Happy": 100, "Disgust": -30, "Surprise": -25, "Neutral": 50, "Sad": -50}, 
        "Anger": 'Is this your father\'s road for you to block it like you own it? Get out of the way before I really lose my temper!', 
        "Fear": '(Annoyed) I don\'t care about that, can you just get out of my way quickly. If I get any later, it will be a disaster.', 
        "Happy": '(Smiling with Visible Urgency) Fine. It looks like nothing can be done at the moment except wait.', 
        "Disgust": 'Is this your father\'s road for you to block it like you own it? Get out of the way right now!', 
        "Surprise": 'WOW! what an excuse.', 
        "Neutral": '(Expressionless) OK. It looks like nothing can be done at the moment except wait.', 
        "Sad": '(Monotonous) I don\'t care about that, can you just get out of my way. If I get any later, it will be a disaster.', 
        "End": '(Muttering Again) I should have left early by atleast an hour or so.', 
        "Next": 20, 
    }, 
    {
        "scnImg": "rdBlk1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''Fortunately, after a couple of minutes, the lady gets enough space for her BMW, and clears the way for {user}.''', 
        "emotional": False, 
        "Next": 21, 
    }, 
    {
        "scnImg": "trafic3.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''Finally, after wrestling with the Mumbai traffic, {user} arrives at the venue. However, he was half an hour late.''', 
        "emotional": False, 
        "Next": 22, 
    }, 
    {
        "scnImg": "entry1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''Despite his best efforts, {user}'s arrival at the venue was marked by apologies and hurried explanations. ''', 
        "emotional": False, 
        "Next": 23, 
    }, 
    {
        "scnImg": "entry2.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''But then, X's Tech Lead, Mr. Sarath approaches {user}. He feels that {user} robbed him of the chance to be the CEO of X.''', 
        "emotional": False, 
        "Next": 24, 
    }, 
    {
        "scnImg": "entry2.jpg", 
        "chrImg": "sarath.png", 
        "name": f"Mr. Sarath (X's Tech Lead)",  
        "body": f'''Oh! Finally you arrive, I was almost convinced you'd chickened out and wouldn't show up.''', 
        "emotional": False, 
        "Next": 25, 
    }, 
    {
        "scnImg": "entry2.jpg", 
        "chrImg": "verma.png", 
        "name": f"{user} (You)", 
        "body": f'''(Mumbling) Why did he pop up right in front of me before the big event?!''', 
        "emotional": True, 
        "Points": {"Anger": -100, "Fear": -50, "Happy": -25, "Disgust": -75, "Surprise": 50, "Neutral": -10, "Sad": 30}, 
        "Anger": '(Lividly) Rats like you won\'t last long here as I\'ll be in-charge. I wonder how the previous CEO tolerated you.', 
        "Fear": '(Anxiously) Stop it Sharath. Don\'t stress me right now.', 
        "Happy": '(With a Mocking Laugh) Cut the crap, Sharath. Just wait and watch me become the permanent CEO of X.', 
        "Disgust": '(Offensively) You won\'t last long here, once I\'ll be in-charge. I wonder how the previous CEO tolerated you.', 
        "Surprise": 'Huh! No way I would miss this opportunity to become the permanent CEO of X.', 
        "Neutral": '(With a Poker Face) Cut the crap, Sharath. Just wait and watch the show.', 
        "Sad": '(With a Disheartened Face) Stop it Sharath. I am already tensed as it is.', 
        "End": 'And you know what? This is not the right time for it.', 
        "Next": 26, 
    }, 
    {
        "scnImg": "entry2.jpg", 
        "chrImg": "sarath.png", 
        "name": f"Sarath",  
        "body": f'''Yeah fine, Whatever . . .''', 
        "emotional": False, 
        "Next": 27, 
    }, 
    {
        "scnImg": "lobby1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''After the spicy conversation, {user} arrives at the lobby where he meets none other than X's Owner, Mr. Travis.''', 
        "emotional": False, 
        "Next": 28, 
    }, 
    {
        "scnImg": "lobby1.jpg", 
        "chrImg": "travis.png", 
        "name": f"Mr. Travis (X's Owner)",   
        "body": f'''I didn\'t expect this from you of all people Verma. We already have our hands full with organizing this and now you show up late.''', 
        "emotional": False, 
        "Next": 29, 
    },
    {
        "scnImg": "lobby1.jpg", 
        "chrImg": "verma.png",
        "name": f"{user} (You)", 
        "body": f'''Oh Sir, actually . . .''', 
        "emotional": True, 
        "Points": {"Anger": -100, "Fear": -10, "Happy": 50, "Disgust": -75, "Surprise": 10, "Neutral": 30, "Sad": 10}, 
        "Anger": '(Irritated) I know what I am doing, sir. Now, if you will excuse me.', 
        "Fear": '(Scared) I am sorry sir. I know this is unacceptable, but I assure you that I tried my best to arrive as quickly as I could.', 
        "Happy": 'Chill boss. Everything is fine now that I am here.', 
        "Disgust": '(Vilely) I know what I am doing, sir. Now, if you will excuse me.',  
        "Surprise": '(Excusingly) Sorry sir. I prepared for everything but the traffic came out of the syllabus.', 
        "Neutral": 'I am sorry sir, I\'ll ensure this won\'t happen again.', 
        "Sad": 'I am so sorry sir. I know this is unacceptable, but I assure you that I tried my best to arrive as quickly as I could.', 
        "End": '(Thinking) I need to avoid these conversations on being late. They are starting to frustrate me now.', 
        "Next": 30, 
    },  
    {
        "scnImg": "lobby1.jpg", 
        "chrImg": "travis.png", 
        "name": f"Travis",   
        "body": f'''Okay, Fine now. All the best Verma. Don't disappoint me.''', 
        "emotional": False, 
        "Next": 31, 
    },        
    {
        "scnImg": "lobby1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''As soon as the conversation ends, {user}'s friends, Rohit and Rahul, approach him . . .''', 
        "emotional": False, 
        "Next": 32, 
    },
    {
        "scnImg": "lobby2.jpg", 
        "chrImg": "rohit.png", 
        "name": f"Rohit (A Senior-SDE at X)", 
        "body": f'''Ready for your big day? Verma Bhai.''', 
        "emotional": False, 
        "Next": 33, 
    },
    {
        "scnImg": "lobby2.jpg", 
        "chrImg": "rahul.png", 
        "name": f"Rahul (A SDE at X)", 
        "body": f'''Don\'t embarrass yourself out there.''', 
        "emotional": False, 
        "Next": 34, 
    },
    {
        "scnImg": "lobby2.jpg", 
        "chrImg": "verma.png",
        "name": f"{user} (You)", 
        "body": f'''(Muttering) I hope the boss won't be angry, considering the shortage of the time I have . . .''', 
        "emotional": True, 
        "Points": {"Anger": -75, "Fear": -20, "Happy": 50, "Disgust": -75, "Surprise": 25, "Neutral": -25, "Sad": -50}, 
        "Anger": '(With Urgency) Move out of my way!', 
        "Fear": 'Yikes! You two startled me.', 
        "Happy": 'Yeah, Sure Bhai-Log!', 
        "Disgust": '(Ignoring) Out of the way guys!',  
        "Surprise": 'Whoa! You two startled me.', 
        "Neutral": 'Yes, I am ready.', 
        "Sad": '(In a Dull Tone) Oh you guys.', 
        "End": 'I\'ll talk to you guys after the meeting.',
        "Next": 35,
    },    
    {
        "scnImg": "penaltimate1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''Rohit and Rahul wish him luck, and {user} rushes to the presentation hall, while doing the final preparations.''', 
        "emotional": False, 
        "Next": 36, 
    },
    {
        "scnImg": "penaltimate2.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''But, at the entrance, he sees Jane, the PR Lead of the company, who seemed concerned about somthing . . .''', 
        "emotional": False, 
        "Next": 37, 
    },
    {
        "scnImg": "penaltimate2.jpg", 
        "chrImg": "jane.png", 
        "name": f"Jane (X's PR Lead)", 
        "body": f'''{user}, I heard some murmurs about a group of disgruntled employees. They are planning a coup to damage your reputation.''', 
        "emotional": False, 
        "Next": 38, 
    },
    {
        "scnImg": "penaltimate2.jpg", 
        "chrImg": "verma.png", 
        "name": f"{user} (You)", 
        "body": f'''I don't know what to say right now but . . .''', 
        "emotional": True, 
        "Points": {"Anger": -75, "Fear": -50, "Happy": 20, "Disgust": -10, "Surprise": 20, "Neutral": 0, "Sad": 0}, 
        "Anger": '(Furious) Let them try, I will completely destroy their careers.', 
        "Fear": '(Tensed) I didn\'t know something omnious like this was happening right behind our backs.', 
        "Happy": '(Smiling Lightly) Well, now that the pressure is on, I will blow them away and make them accept me as the CEO.', 
        "Disgust": '(Mockingly) Let them try, I will crush them.', 
        "Surprise": 'Oh no! IDK why are most things trying to cause trouble today. Anyways, I need to pull it off somehow.', 
        "Neutral": '(Feeling Betrayed) I didn\'t know something like this was happening right behind our backs.', 
        "Sad": '(Heartbroken) I didn\'t know something disastrous like this was happening right behind our backs.',  
        "End": 'Thanks for the alert though.', 
        "Next": 39, 
    }, 
    {
        "scnImg": "ultimate1.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''Ultimately, {user} begins the presentation. He starts with formalities and then moves on to some preliminary technical stuff.''', 
        "emotional": False, 
        "Next": 40, 
    },
    {
        "scnImg": "ultimate2.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''The Chief Guest's arrival is imminent, and the atmosphere buzzes with anticipation.''', 
        "emotional": False, 
        "Next": 41, 
    },
    {
        "scnImg": "ultimate2.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator", 
        "body": f'''Suddenly, {user} notices a group led by Sharath approaching him, and he braces himself for the worst.''', 
        "emotional": False, 
        "Next": 42, 
    },
    {
        "scnImg": "ultimate3.jpg", 
        "chrImg": "sarath.png", 
        "name": f"Sarath", 
        "body": f'''You are inexperienced! We know the reason you were hired was because of some nepotism. We advise you to step down.''',  
        "emotional": False, 
        "Next": 43, 
    },
    {
        "scnImg": "ultimate3.jpg", 
        "chrImg": "teamEvil.png", 
        "name": f"Sarath's Posse ", 
        "body": f'''(Shouting with Determination) DOWN WITH VERMA!!! DOWN WITH VERMA!!!''',  
        "emotional": False, 
        "Next": 44, 
    },
    {
        "scnImg": "ultimate3.jpg", 
        "chrImg": "verma.png",  
        "name": f"{user} (You)", 
        "body": f'''(Firmly with Frustration) Step down you say? That won't happen.''', 
        "emotional": True, 
        "Points": {"Anger": -75, "Fear": -50, "Happy": 25, "Disgust": -75, "Surprise": 25, "Neutral": 50, "Sad": 25}, 
        "Anger": 'How dare you?! Your greed has made you go crazy. I will fix this by taking care of corrupt rats like you first.', 
        "Fear": '(Panics) I trusted you Sharath! How can you do this now? You all know how hard I work for our company.', 
        "Happy": '(Smiles) Look Sharath, we went through thick and thin together, please be cooperative. Greed is a bad thing.', 
        "Disgust": 'How dare you?! Your greed has made you go mad. I will fix this company by taking care of corrupt rats like you first.', 
        "Surprise": 'Alas! I trusted you Sharath. How can you do this? You all know how hard I work for our company.',
        "Neutral": 'Sharath, we went through thick and thin together, please be cooperative. Greed is a scary thing, isn\'t it?', 
        "Sad": '(Sobs) I trusted you Sharath! How can you do something like this right now? You all know how hard I work for X.', 
        "End": 'Don\'t be greedy this much that you all start spelling non-sense during the worst of all times.', 
        "Next": 45, 
    }, 
    {
        "scnImg": "dreamCrowd2.jpg", 
        "chrImg": "narrator.png", 
        "name": f"The Narrator - Conclusion", 
        "body": f'''Find out - "Did Verma stand strong or was he fumbled by the coup?" in the next part of VERMA\'s KARMA. Thanks For Playing!''',  
        "emotional": False,
        "conclude":True,
        "Next": 0, 
    },
    # Part.1 -> Ends
]
